public class AC1 {
    integer a = 10;
    integer b = 15;
    public void method() {
        system.debug('before condition');
        if (a > b) {
            System.debug('a greater than b');
        }
        //test
        system.debug('a is less than B');
        // system.debug('after the condition Satish1');
        system.debug('a is less than B');
        system.debug('a is less than B');
    }

}