public class AppexClassEx01 {
    //variable defination
    String First_name, Last_name;
    
    // Method Defination
    public void DisplayNames(){
        First_name = 'Sam';
        Last_name = 'Sundher';
        System.debug('Welcome to programatic approach App development using Apex');
        System.debug(First_name);
        System.debug('The Value of lastname Variable is : '+Last_name);
        
    }

}